quotesArr = [
  "Bed rest and a large steaming mug of hot chocolate. I always find that cheers me up.",
  "Understanding is the first step to acceptance, and only with acceptance can there be recovery.",
  "Time is making fools of us again.",
  "it matters not what someone is born, but what they grow to be!",
  "It is our choices that show what we truly are, far more than our abilities.",
  "One can never have enough socks.",
  "Alas! Earwax.",
  "It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.",
  "We are only as strong as we are united, as weak as we are divided.",
  "Differences of habit and language are nothing at all if our aims are identical and our hearts are open.",
  "Help will always be given at Hogwarts to those who ask for it.",
  "It does not do to dwell on dreams and forget to live.",
  "Of course it is happening inside your head  but why on earth should that mean that it is not real?",
  "To the well-organized mind, death is but the next great adventure.",
  "Do not pity the dead. Pity the living, and, above all those who live without love.",
  "The truth is a beautiful and terrible thing, and should therefore be treated with great caution.",
  "Numbing the pain for a while will make it worse when you finally feel it.",
  "It is a curious thing but perhaps those who are best suited to power are those who have never sought it.",
  "Happiness can be found even in the darkest times if one only remembers to turn on the light.",
  "Let us step into the night and pursue that flighty temptress, adventure.",
  "We must all face the choice between what is right and what is easy.",
  "For in dreams we enter a world that is entirely our own. ",
  "The best of us sometimes eat our words.",
  "Youth can not know how age thinks and feels, but old men are guilty if they forget what it is to be young.",
  "It is the unknown we fear when we look upon death and darkness. Nothing more.",
  "While we may come from different places and speak in different tongues, our hearts beat as one.",
  "Pain is part of being human . . . the fact that you can feel pain like this is your greatest strength.",
  "As much money and life as you could want! The two things most human beings would choose above all - the trouble is, humans do have a knack of choosing precisely those things that are worst for them.",
  "We must try not to sink beneath our anguish . . . but battle on.",
]
